name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset: [dev, release]
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up ROOT
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: rucio-root-plugin
          create-args: >-
            cxx-compiler
            cmake
            make
            nlohmann_json
            root
          cache-environment: true

      - name: Build ${{ matrix.preset }} preset
        run: cmake --workflow --preset "${{ matrix.preset }}"

      - name: Test ${{ matrix.preset }} preset
        run: ctest --preset "${{ matrix.preset }}"
