name: CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Check out sources
        uses: actions/checkout@v4

      - name: Set up ROOT
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: rucio-root-plugin
          create-args: >-
            cxx-compiler
            cmake
            make
            nlohmann_json
            root
          cache-environment: true

      - name: Build
        run: cmake --workflow --preset dev

      - name: Test
        run: ctest --test-dir build-dev --output-on-failure
